require_relative "commands/clear"
require_relative "commands/colour"
require_relative "commands/horizontal_segment"
require_relative "commands/initialize"
require_relative "commands/show"
require_relative "commands/vertical_segment"
